export const userinfo = [
    {
        name: "Karak XP earned",
        content: 'Your total XP rewards earned by restaking assets on Karak',
        logoName: 'karak-logo',
        logoSrc: '../../assets/karak-logo.png',
        logoSrcSet: '../../assets/karak-logo.png',
        nameColor: 'text-light-black',
        balance: 0,
        backColor: 'bg-white shadow-md',
        contentColor: "text-light-black",
        viewStyle: {},
    },
    {
        name: "Users referred to Karak",
        content: 'The amount of users you\'ve referred to Karak',
        logoName: 'btc-logo',
        logoSrc: '../../assets/btc-logo.png',
        logoSrcSet: '../../assets/btc-logo.png',
        nameColor: 'text-light-black',
        balance: "0",
        backColor: 'bg-white shadow-md',
        contentColor: "text-light-black",
        viewStyle: {},
    },
];
