export const xpearned = [
    {
        name: "Restaking XP",
        content: 'Your total XP rewards earned by restaking assets on Mad',
        logoName: 'Mad-logo',
        logoSrc: 'Mad-logo.png',
        logoSrcSet: '../../assets/Mad-logo.png',
        nameColor: 'text-light-black',
        balance: 0,
        backColor: 'bg-secondary-orange',
        contentColor: "text-light-black",
        viewStyle: {},
    },
    {
        name: "BTC Restaked",
        content: 'Your total BTC restaked',
        logoName: 'btc-logo',
        logoSrc: '../../assets/btc-logo.png',
        logoSrcSet: '../../assets/btc-logo.png',
        nameColor: 'text-white',
        balance: "0.00",
        backColor: 'bg-light-orange',
        contentColor: "text-gray-100",
        viewStyle: { textShadow: 'rgba(0, 0, 0, 0.25) 0px 4px 4px' },
    },
    {
        name: "ETH Restaked",
        content: 'Your total ETH restaked',
        logoName: 'eth-logo',
        logoSrc: '../../assets/eth-logo.png',
        logoSrcSet: '../../assets/eth-logo.png',
        nameColor: 'text-white',
        balance: "0.00",
        backColor: 'bg-blue-gray',
        contentColor: "text-gray-100",
        viewStyle: { textShadow: 'rgba(0, 0, 0, 0.25) 0px 4px 4px' },
    },
    {
        name: "USD Restaked",
        content: 'Your total USD restaked',
        logoName: 'usd-logo',
        logoSrc: '../../assets/usd-logo.png',
        logoSrcSet: '../../assets/usd-logo.png',
        nameColor: 'text-white',
        balance: "0.00",
        backColor: 'bg-primary-blue',
        contentColor: "text-gray-100",
        viewStyle: { textShadow: 'rgba(0, 0, 0, 0.25) 0px 4px 4px' },
    },
];
